packages:
  - apps/*
  - packages/*

catalog:
  '@types/eslint': ^19
  '@types/node': ^22
  eslint: ^9.39.2
  typescript: ^5.9.2

catalogs:
  react19:
    '@types/react': ^19.1.0
    '@types/react-dom': ^19.1.1
    react: ^19.1.0
    react-dom: ^19.1.0
