packages:
  - "apps/*"
  - "packages/*"

catalog:
  eslint: ^9.34.0
  typescript: ^5.9.2
  "@types/node": ^22
  "@types/eslint": ^19

catalogs:
  react19:
    react: ^19.1.0
    react-dom: ^19.1.0
    "@types/react": ^19.1.0
    "@types/react-dom": ^19.1.1
