import { Template } from '@/payload-types'
import { generateId } from '@/utils/generate-id'
import { CollectionBeforeOperationHook } from 'payload'
import slugify from 'slugify'
import { createOrUpdateTags } from './Tags.hooks'
